name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: urlpushserver.rs
  DOCKERHUB_USERNAME: zottelchen

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # This is a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # So now you can use Actions' own caching!
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zottelchen/urlpushserver.rs:latest, zottelchen/urlpushserver.rs:${GITHUB_SHA::8}
          cache-from: type=registry,src=/tmp/.buildx-cache
          cache-to: type=registry,dest=/tmp/.buildx-cache-new,mode=max